version: "3"
services:
  localhost:
    image: postgres:latest
    container_name: reddit-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./data:/var/lib/postgresql/data
